FROM azul/zulu-openjdk:25-latest

WORKDIR /template
COPY . .
COPY --from=hairyhenderson/gomplate:stable /gomplate /bin/gomplate

# sanity check
RUN java -jar sportpaper-1.8.8.jar -v

WORKDIR /server

EXPOSE 25565
ENTRYPOINT [ "/template/bootstrap.sh" ]
