name: ci

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  PUSH_BACKEND_IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/bradyverse-backend:standalone
  STANDALONE: true

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          ./build.sh
